""" Complete product catalog for Myntra Mini. """

CATALOG = [
  {
    "id": "pun-01",
    "name": "Royal Patiala Salwar Suit with Heavy Phulkari Dupatta",
    "price": 2999,
    "category": "ethnic wear",
    "gender": "women",
    "color": "Magenta Pink & Gold",
    "pattern": "embroidered",
    "style": "patiala suit",
    "occasion": "festival",
    "image_url": "https://ranaphulkari.com/cdn/shop/files/72759c27-1b96-41b2-be6c-0528150cb4c5_c7375295-02e6-4f12-b609-233e239f0bb3.png?v=1766152356&width=2000",
    "brand": "BIBA",
    "mrp": 4999,
    "discount_percent": 40,
    "rating": 4.8,
    "review_count": 3420,
    "region_relevance": ["Punjab", "Chandigarh", "Delhi", "Haryana"],
    "city_trend_score": {"Amritsar": 98, "Ludhiana": 95, "Chandigarh": 92, "Delhi": 88, "Mumbai": 30, "Bengaluru": 25},
    "festival_relevance": ["Lohri", "Baisakhi", "Karwa Chauth"],
    "styleTags": ["patiala suit", "phulkari", "punjabi suit", "zari", "lohri", "baisakhi"],
    "local_purchase_count": 6120,
    "local_trending_tag": "Amritsar & Ludhiana #1 Baisakhi & Lohri Festive Pick"
  },
  {
    "id": "pun-02",
    "name": "Royal Punjabi Silk Kurta Pajama with Embroidered Nehru Jacket",
    "price": 3499,
    "category": "ethnic wear",
    "gender": "men",
    "color": "Royal Maroon & Gold",
    "pattern": "embroidered",
    "style": "kurta pajama",
    "occasion": "wedding",
    "image_url": "https://tse2.mm.bing.net/th/id/OIP.tqm6LjxvBX0B1tuxQ_3ACQHaJ4?r=0&pid=Api&P=0&h=180",
    "brand": "Manyavar",
    "mrp": 5999,
    "discount_percent": 42,
    "rating": 4.7,
    "review_count": 2150,
    "region_relevance": ["Punjab", "Chandigarh", "Delhi", "Haryana"],
    "city_trend_score": {"Ludhiana": 96, "Chandigarh": 94, "Amritsar": 91, "Delhi": 85, "Chennai": 20, "Kolkata": 22},
    "festival_relevance": ["Diwali", "Baisakhi", "Wedding Season"],
    "styleTags": ["kurta pajama", "nehru jacket", "royal", "wedding", "punjabi"],
    "local_purchase_count": 4820,
    "local_trending_tag": "Ludhiana & Chandigarh Shaadi Festive Favorite"
  },
  {
    "id": "raj-01",
    "name": "Hand-Block Printed Bandhani Saree with Gota Patti",
    "price": 2499,
    "category": "saree",
    "gender": "women",
    "color": "Royal Red & Gold",
    "pattern": "bandhani",
    "style": "gota patti",
    "occasion": "wedding",
    "image_url": "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600&auto=format&fit=crop&q=80",
    "brand": "Anouk",
    "mrp": 4999,
    "discount_percent": 50,
    "rating": 4.8,
    "review_count": 3800,
    "region_relevance": ["Rajasthan", "Gujarat", "Delhi"],
    "city_trend_score": {"Jaipur": 98, "Udaipur": 94, "Ahmedabad": 90, "Delhi": 86, "Kochi": 18, "Guwahati": 20},
    "festival_relevance": ["Teej", "Navratri", "Diwali"],
    "styleTags": ["bandhani", "tie and dye", "gotapatti", "jaipur print", "teej", "navratri"],
    "local_purchase_count": 5950,
    "local_trending_tag": "Jaipur Teej & Wedding Bestseller"
  },
  {
    "id": "raj-02",
    "name": "Royal Jodhpuri Silk Achkan Kurta Set with Stole",
    "price": 4299,
    "category": "ethnic wear",
    "gender": "men",
    "color": "Imperial Royal Blue",
    "pattern": "solid",
    "style": "jodhpuri achkan",
    "occasion": "wedding",
    "image_url": "https://tse2.mm.bing.net/th/id/OIP.tMI9hX7aYnhhrBD-DU9N_wHaLe?r=0&pid=Api&P=0&h=180",
    "brand": "FabIndia",
    "mrp": 7500,
    "discount_percent": 43,
    "rating": 4.9,
    "review_count": 2100,
    "region_relevance": ["Rajasthan", "Gujarat", "Delhi", "Uttar Pradesh"],
    "city_trend_score": {"Jodhpur": 97, "Udaipur": 95, "Jaipur": 92, "Lucknow": 84, "Bengaluru": 25, "Patna": 30},
    "festival_relevance": ["Diwali", "Wedding Season", "Royal Festivities"],
    "styleTags": ["jodhpuri", "achkan", "royal", "silk", "marwar"],
    "local_purchase_count": 3890,
    "local_trending_tag": "Jodhpur & Udaipur Groom Heritage Favorite"
  },
  {
    "id": "guj-01",
    "name": "Mirror-Work Heavy Chaniya Choli",
    "price": 3999,
    "category": "ethnic wear",
    "gender": "women",
    "color": "Vibrant Yellow & Bandhej Pink",
    "pattern": "mirror work",
    "style": "chaniya choli",
    "occasion": "festival",
    "image_url": "https://i.pinimg.com/originals/ea/f1/99/eaf199f6a3a55c9d4df3db6f704b7c44.png",
    "brand": "Kalaniketan",
    "mrp": 6999,
    "discount_percent": 43,
    "rating": 4.9,
    "review_count": 4200,
    "region_relevance": ["Gujarat", "Rajasthan", "Maharashtra"],
    "city_trend_score": {"Ahmedabad": 99, "Surat": 97, "Vadodara": 95, "Mumbai": 88, "Chennai": 15, "Chandigarh": 20},
    "festival_relevance": ["Navratri", "Garba", "Sharad Purnima"],
    "styleTags": ["chaniya choli", "mirror work", "garba", "navratri", "bandhani"],
    "local_purchase_count": 6780,
    "local_trending_tag": "Ahmedabad & Surat Navratri #1 Choice"
  },
  {
    "id": "guj-02",
    "name": "Authentic Rajkot Single Patola Silk Saree",
    "price": 4999,
    "category": "saree",
    "gender": "women",
    "color": "Crimson Red & Mustard Gold",
    "pattern": "patola weave",
    "style": "patola silk",
    "occasion": "wedding",
    "image_url": "https://tse4.mm.bing.net/th/id/OIP.X1yya9Ob6-pb_Z40EFphYgHaKt?r=0&pid=Api&P=0&h=180",
    "brand": "Nalli",
    "mrp": 8999,
    "discount_percent": 44,
    "rating": 4.8,
    "review_count": 2890,
    "region_relevance": ["Gujarat", "Maharashtra", "Delhi"],
    "city_trend_score": {"Vadodara": 96, "Rajkot": 98, "Ahmedabad": 93, "Mumbai": 86, "Kolkata": 25, "Shimla": 12},
    "festival_relevance": ["Diwali", "Navratri", "Wedding Season"],
    "styleTags": ["patola", "silk", "handloom", "traditional", "rajkot"],
    "local_purchase_count": 4120,
    "local_trending_tag": "Vadodara & Rajkot Heritage Favorite"
  },
  {
    "id": "up-01",
    "name": "Hand-Crafted Lucknowi Chikankari Pure Cotton Kurta",
    "price": 1899,
    "category": "ethnic wear",
    "gender": "men",
    "color": "Ivory White",
    "pattern": "chikankari embroidery",
    "style": "lucknowi kurta",
    "occasion": "festival",
    "image_url": "https://nazranachikan.com/cdn/shop/files/1_2682e5ba-380e-4e54-865a-ea7ba76b9a05_1080x1080.jpg?v=1763043009",
    "brand": "Manyavar",
    "mrp": 3499,
    "discount_percent": 46,
    "rating": 4.9,
    "review_count": 5400,
    "region_relevance": ["Uttar Pradesh", "Delhi", "Bihar"],
    "city_trend_score": {"Lucknow": 99, "Kanpur": 96, "Varanasi": 92, "Delhi": 90, "Bengaluru": 35, "Kochi": 15},
    "festival_relevance": ["Eid", "Holi", "Diwali"],
    "styleTags": ["lucknowi", "chikankari", "handwork", "royal", "eid"],
    "local_purchase_count": 7890,
    "local_trending_tag": "Lucknow & Kanpur Heritage Bestseller"
  },
  {
    "id": "up-02",
    "name": "Pure Banarasi Zari Woven Silk Saree with Temple Border",
    "price": 4599,
    "category": "saree",
    "gender": "women",
    "color": "Deep Emerald Green & Gold",
    "pattern": "zari weave",
    "style": "banarasi silk",
    "occasion": "wedding",
    "image_url": "https://www.pothys.com/cdn/shop/files/9A_81ad2442-0ec7-4a49-9b67-65426a67f436.jpg?v=1784624347&width=800",
    "brand": "Nalli",
    "mrp": 8500,
    "discount_percent": 46,
    "rating": 4.9,
    "review_count": 4100,
    "region_relevance": ["Uttar Pradesh", "Bihar", "Delhi"],
    "city_trend_score": {"Varanasi": 99, "Lucknow": 94, "Patna": 91, "Delhi": 87, "Goa": 18, "Chandigarh": 25},
    "festival_relevance": ["Dev Deepawali", "Diwali", "Wedding Season"],
    "styleTags": ["banarasi", "zari", "pure silk", "varanasi", "temple border"],
    "local_purchase_count": 6420,
    "local_trending_tag": "Varanasi & Dev Deepawali Top Choice"
  },
  {
    "id": "bih-01",
    "name": "Pure Bhagalpuri Tussar Silk Saree",
    "price": 3899,
    "category": "saree",
    "gender": "women",
    "color": "Mustard Gold & Maroon",
    "pattern": "handloom weave",
    "style": "tussar silk",
    "occasion": "festival",
    "image_url": "https://linenworldonline.in/cdn/shop/products/gicha-tussar-saree_2_900x_e8e211b5-14aa-48f7-862b-304419bcf1bd.jpg?v=1628246770&width=800",
    "brand": "FabIndia",
    "mrp": 6500,
    "discount_percent": 40,
    "rating": 4.9,
    "review_count": 5800,
    "region_relevance": ["Bihar", "Jharkhand", "West Bengal"],
    "city_trend_score": {"Patna": 98, "Gaya": 96, "Ranchi": 93, "Kolkata": 88, "Coimbatore": 20, "Surat": 22},
    "festival_relevance": ["Chhath Puja", "Durga Puja", "Makar Sankranti"],
    "styleTags": ["handloom", "pure tussar", "chhath puja", "traditional", "bhagalpuri"],
    "local_purchase_count": 8840,
    "local_trending_tag": "Patna & Gaya Chhath Puja #1 Choice"
  },
  {
    "id": "bih-02",
    "name": "Mithila Handpainted Cotton Kurti",
    "price": 1499,
    "category": "ethnic wear",
    "gender": "women",
    "color": "Sunset Yellow",
    "pattern": "madhubani art print",
    "style": "mithila handpainted",
    "occasion": "festival",
    "image_url": "https://tse4.mm.bing.net/th/id/OIP.XySDqVyxZZm5U1vDXJZQPAHaLH?r=0&pid=Api&P=0&h=180",
    "brand": "Taavi",
    "mrp": 2799,
    "discount_percent": 46,
    "rating": 4.7,
    "review_count": 3200,
    "region_relevance": ["Bihar", "Jharkhand", "Uttar Pradesh"],
    "city_trend_score": {"Darbhanga": 98, "Muzaffarpur": 96, "Patna": 92, "Lucknow": 80, "Jaipur": 28, "Pune": 22},
    "festival_relevance": ["Chhath Puja", "Teej", "Saraswati Puja"],
    "styleTags": ["mithila art", "madhubani", "cotton", "chhath puja", "teej"],
    "local_purchase_count": 5120,
    "local_trending_tag": "Darbhanga & Muzaffarpur Traditional Favorite"
  },
  {
    "id": "bih-03",
    "name": "Traditional Pure Cotton Dhoti Kurta with Silk Stole",
    "price": 2199,
    "category": "ethnic wear",
    "gender": "men",
    "color": "Kesar Yellow & Off-White",
    "pattern": "solid",
    "style": "dhoti kurta",
    "occasion": "festival",
    "image_url": "https://i.pinimg.com/originals/98/ff/e3/98ffe38ed1c0807ddb93637522a785f9.jpg",
    "brand": "FabIndia",
    "mrp": 3999,
    "discount_percent": 45,
    "rating": 4.8,
    "review_count": 2900,
    "region_relevance": ["Bihar", "Jharkhand", "Uttar Pradesh"],
    "city_trend_score": {"Patna": 97, "Bhagalpur": 95, "Ranchi": 90, "Varanasi": 85, "Ahmedabad": 20, "Bengaluru": 18},
    "festival_relevance": ["Chhath Puja", "Diwali", "Makar Sankranti"],
    "styleTags": ["dhoti kurta", "chhath puja", "traditional", "handloom"],
    "local_purchase_count": 4950,
    "local_trending_tag": "Patna & Bhagalpur Festive Essential"
  },
  {
    "id": "mah-01",
    "name": "Traditional Royal Paithani Silk Saree with Peacock Zari Motif",
    "price": 4999,
    "category": "saree",
    "gender": "women",
    "color": "Emerald Green & Gold",
    "pattern": "peacock zari motif",
    "style": "paithani silk",
    "occasion": "wedding",
    "image_url": "https://www.zarikaariindia.com/cdn/shop/products/13_0b6612c8-dce6-4166-adef-56bdbb72d809_1200x.jpg?v=1656832695",
    "brand": "Kalaniketan",
    "mrp": 8999,
    "discount_percent": 44,
    "rating": 4.9,
    "review_count": 4800,
    "region_relevance": ["Maharashtra", "Goa"],
    "city_trend_score": {"Mumbai": 98, "Pune": 97, "Nashik": 94, "Nagpur": 91, "Panaji": 82, "Delhi": 25},
    "festival_relevance": ["Ganesh Chaturthi", "Gudi Padwa", "Diwali"],
    "styleTags": ["paithani", "silk", "zari border", "peacock motif", "ganesh chaturthi"],
    "local_purchase_count": 7210,
    "local_trending_tag": "Mumbai & Pune Ganesh Utsav Favorite"
  },
  {
    "id": "mah-02",
    "name": "Royal Peshwai Silk Kurta Set with Zari Dupatta",
    "price": 3299,
    "category": "ethnic wear",
    "gender": "men",
    "color": "Royal Purple & Gold",
    "pattern": "woven zari",
    "style": "peshwai kurta",
    "occasion": "festival",
    "image_url": "https://thecloset.co.in/wp-content/uploads/2026/05/Royal-Satori-Silk-Kurta-Set-with-Banarasi-Zari-Dupatta-10.jpeg",
    "brand": "Manyavar",
    "mrp": 5499,
    "discount_percent": 40,
    "rating": 4.7,
    "review_count": 2600,
    "region_relevance": ["Maharashtra", "Goa"],
    "city_trend_score": {"Pune": 97, "Nagpur": 95, "Mumbai": 93, "Kolhapur": 90, "Jaipur": 22, "Lucknow": 20},
    "festival_relevance": ["Ganesh Chaturthi", "Gudi Padwa", "Diwali"],
    "styleTags": ["peshwai", "kurta", "ganesh chaturthi", "gudi padwa"],
    "local_purchase_count": 4350,
    "local_trending_tag": "Pune & Nagpur Festive Favorite"
  },
  {
    "id": "wb-01",
    "name": "Pure Garad Red-Border Jamdani Silk Saree",
    "price": 4299,
    "category": "saree",
    "gender": "women",
    "color": "Ivory White & Red Border",
    "pattern": "jamdani weave",
    "style": "garad silk",
    "occasion": "festival",
    "image_url": "https://www.pothys.com/cdn/shop/files/9A_81ad2442-0ec7-4a49-9b67-65426a67f436.jpg?v=1784624347&width=800",
    "brand": "FabIndia",
    "mrp": 7999,
    "discount_percent": 46,
    "rating": 4.9,
    "review_count": 5300,
    "region_relevance": ["West Bengal", "Odisha", "Assam"],
    "city_trend_score": {"Kolkata": 99, "Howrah": 96, "Siliguri": 92, "Bhubaneswar": 85, "Guwahati": 82, "Ahmedabad": 18},
    "festival_relevance": ["Durga Puja", "Poila Baisakh", "Kali Puja"],
    "styleTags": ["garad", "jamdani", "durga puja", "taant", "pure silk"],
    "local_purchase_count": 8120,
    "local_trending_tag": "Kolkata Durga Puja #1 Bestseller"
  },
  {
    "id": "wb-02",
    "name": "Kantha-Stitch Hand-Embroidered Silk Kurta",
    "price": 2299,
    "category": "ethnic wear",
    "gender": "men",
    "color": "Mustard Yellow",
    "pattern": "kantha stitch",
    "style": "kantha embroidered",
    "occasion": "festival",
    "image_url": "https://tse1.mm.bing.net/th/id/OIP.5HlTgLYFTCASmHph-I8D1wHaLH?r=0&pid=Api&P=0&h=180",
    "brand": "Taavi",
    "mrp": 3999,
    "discount_percent": 43,
    "rating": 4.7,
    "review_count": 2400,
    "region_relevance": ["West Bengal", "Odisha", "Jharkhand"],
    "city_trend_score": {"Kolkata": 97, "Howrah": 94, "Asansol": 90, "Ranchi": 82, "Delhi": 30, "Chennai": 18},
    "festival_relevance": ["Poila Baisakh", "Durga Puja", "Saraswati Puja"],
    "styleTags": ["kantha stitch", "handloom", "poila baisakh", "kolkata"],
    "local_purchase_count": 3980,
    "local_trending_tag": "Kolkata & Howrah Festive Pick"
  },
  {
    "id": "odi-01",
    "name": "Traditional Sambalpuri Handloom Ikat Silk Saree",
    "price": 4199,
    "category": "saree",
    "gender": "women",
    "color": "Pasapalli Red & Black",
    "pattern": "ikat pasapalli",
    "style": "sambalpuri ikat",
    "occasion": "festival",
    "image_url": "https://www.nalli.com/cdn/shop/files/NF2958494_M.jpg?v=1769777916&width=1024",
    "brand": "Nalli",
    "mrp": 7500,
    "discount_percent": 44,
    "rating": 4.8,
    "review_count": 2700,
    "region_relevance": ["Odisha", "West Bengal", "Chhattisgarh"],
    "city_trend_score": {"Bhubaneswar": 98, "Cuttack": 96, "Sambalpur": 95, "Raipur": 83, "Kolkata": 81, "Surat": 20},
    "festival_relevance": ["Ratha Yatra", "Raja Parba", "Durga Puja"],
    "styleTags": ["sambalpuri", "ikat", "handloom", "ratha yatra"],
    "local_purchase_count": 4300,
    "local_trending_tag": "Bhubaneswar & Cuttack Ratha Yatra Pick"
  },
  {
    "id": "tn-01",
    "name": "Kanjeevaram Pure Gold Zari Woven Silk Saree",
    "price": 5499,
    "category": "saree",
    "gender": "women",
    "color": "Kanya Red & Temple Gold",
    "pattern": "temple border zari",
    "style": "kanjeevaram silk",
    "occasion": "wedding",
    "image_url": "https://www.prashantisarees.com/cdn/shop/files/8_1.jpg?v=1727114507",
    "brand": "Nalli",
    "mrp": 9999,
    "discount_percent": 45,
    "rating": 4.9,
    "review_count": 5100,
    "region_relevance": ["Tamil Nadu", "Karnataka", "Kerala"],
    "city_trend_score": {"Chennai": 99, "Madurai": 97, "Coimbatore": 95, "Bengaluru": 91, "Kochi": 86, "Jaipur": 20},
    "festival_relevance": ["Pongal", "Wedding Season", "Varalakshmi Vratam"],
    "styleTags": ["kanjeevaram", "pure silk", "gold zari", "temple border", "pongal"],
    "local_purchase_count": 7880,
    "local_trending_tag": "Chennai & Madurai Wedding & Pongal Pick"
  },
  {
    "id": "tn-02",
    "name": "Traditional Pure Silk Veshti & Angavastram Set",
    "price": 2499,
    "category": "ethnic wear",
    "gender": "men",
    "color": "Cream & Gold Zari",
    "pattern": "zari border",
    "style": "veshti",
    "occasion": "festival",
    "image_url": "https://tse4.mm.bing.net/th/id/OIP.etQxIELe7MuSUdOVTe2AmgHaHa?r=0&pid=Api&P=0&h=180",
    "brand": "Manyavar",
    "mrp": 4499,
    "discount_percent": 44,
    "rating": 4.8,
    "review_count": 3400,
    "region_relevance": ["Tamil Nadu", "Karnataka", "Kerala"],
    "city_trend_score": {"Chennai": 98, "Coimbatore": 96, "Madurai": 94, "Bengaluru": 88, "Kochi": 85, "Patna": 15},
    "festival_relevance": ["Pongal", "Vishu", "Traditional Weddings"],
    "styleTags": ["veshti", "angavastram", "pongal", "pure silk", "traditional"],
    "local_purchase_count": 5320,
    "local_trending_tag": "Chennai & Coimbatore Pongal Essential"
  },
  {
    "id": "ker-01",
    "name": "Kasavu Gold Border Handloom Cotton Saree",
    "price": 2899,
    "category": "saree",
    "gender": "women",
    "color": "Off-White & Gold Kasavu",
    "pattern": "kasavu zari border",
    "style": "kerala kasavu",
    "occasion": "festival",
    "image_url": "https://tse3.mm.bing.net/th/id/OIP.59xzHD7jphADUiR7P8QW1gHaLH?r=0&pid=Api&P=0&h=180",
    "brand": "FabIndia",
    "mrp": 4999,
    "discount_percent": 42,
    "rating": 4.9,
    "review_count": 4100,
    "region_relevance": ["Kerala", "Tamil Nadu", "Karnataka"],
    "city_trend_score": {"Kochi": 99, "Trivandrum": 97, "Kozhikode": 95, "Chennai": 85, "Bengaluru": 83, "Lucknow": 16},
    "festival_relevance": ["Onam", "Vishu", "Temple Festivals"],
    "styleTags": ["kasavu", "onam", "gold zari", "handloom", "kerala saree"],
    "local_purchase_count": 6200,
    "local_trending_tag": "Kochi & Trivandrum Onam #1 Choice"
  },
  {
    "id": "kar-01",
    "name": "Royal Mysore Gold Zari Silk Saree",
    "price": 4899,
    "category": "saree",
    "gender": "women",
    "color": "Royal Maroon & Mysore Gold",
    "pattern": "solid zari border",
    "style": "mysore silk",
    "occasion": "wedding",
    "image_url": "https://www.nalli.com/cdn/shop/files/NF2958494_M.jpg?v=1769777916&width=1024",
    "brand": "Nalli",
    "mrp": 8499,
    "discount_percent": 42,
    "rating": 4.8,
    "review_count": 3300,
    "region_relevance": ["Karnataka", "Tamil Nadu", "Maharashtra"],
    "city_trend_score": {"Bengaluru": 98, "Mysore": 99, "Hubli": 92, "Chennai": 84, "Mumbai": 80, "Varanasi": 20},
    "festival_relevance": ["Mysore Dasara", "Gowri Habba", "Ugadi"],
    "styleTags": ["mysore silk", "dasara", "gold zari", "karnataka"],
    "local_purchase_count": 5100,
    "local_trending_tag": "Bengaluru & Mysore Dasara Special"
  },
  {
    "id": "tel-01",
    "name": "Pochampally Pure Ikat Silk Saree",
    "price": 4399,
    "category": "saree",
    "gender": "women",
    "color": "Magenta & Royal Blue",
    "pattern": "ikat geometric weave",
    "style": "pochampally ikat",
    "occasion": "festival",
    "image_url": "https://i.etsystatic.com/25108536/r/il/2a2586/6054347944/il_794xN.6054347944_55od.jpg",
    "brand": "FabIndia",
    "mrp": 7800,
    "discount_percent": 44,
    "rating": 4.8,
    "review_count": 3100,
    "region_relevance": ["Telangana", "Andhra Pradesh", "Karnataka"],
    "city_trend_score": {"Hyderabad": 99, "Warangal": 95, "Vijayawada": 92, "Bengaluru": 84, "Kolkata": 22, "Amritsar": 15},
    "festival_relevance": ["Bathukamma", "Sankranti", "Ugadi"],
    "styleTags": ["pochampally", "ikat", "bathukamma", "telangana silk"],
    "local_purchase_count": 4890,
    "local_trending_tag": "Hyderabad Bathukamma Festive Choice"
  },
  {
    "id": "ass-01",
    "name": "Traditional Golden Muga Silk Mekhela Chador",
    "price": 4699,
    "category": "ethnic wear",
    "gender": "women",
    "color": "Golden Muga & Red",
    "pattern": "handwoven motifs",
    "style": "mekhela chador",
    "occasion": "festival",
    "image_url": "https://tse1.mm.bing.net/th/id/OIP.oCZFTjeOw72DP3OgtwrQBgHaNS?r=0&pid=Api&P=0&h=180",
    "brand": "FabIndia",
    "mrp": 8200,
    "discount_percent": 43,
    "rating": 4.9,
    "review_count": 2500,
    "region_relevance": ["Assam", "West Bengal", "Meghalaya"],
    "city_trend_score": {"Guwahati": 99, "Jorhat": 96, "Silchar": 91, "Shillong": 85, "Kolkata": 80, "Mumbai": 18},
    "festival_relevance": ["Rongali Bihu", "Bhogali Bihu", "Durga Puja"],
    "styleTags": ["muga silk", "mekhela chador", "bihu", "handloom"],
    "local_purchase_count": 3820,
    "local_trending_tag": "Guwahati Rongali Bihu Choice"
  },
  {
    "id": "mp-01",
    "name": "Chanderi Silk Cotton Handloom Saree with Zari Border",
    "price": 2799,
    "category": "saree",
    "gender": "women",
    "color": "Teal Green & Gold",
    "pattern": "sheer zari border",
    "style": "chanderi silk",
    "occasion": "festival",
    "image_url": "https://tse2.mm.bing.net/th/id/OIP.liO1xcQwYrySiDcGk_DvlQHaHa?r=0&pid=Api&P=0&h=180",
    "brand": "Anouk",
    "mrp": 4999,
    "discount_percent": 44,
    "rating": 4.7,
    "review_count": 2300,
    "region_relevance": ["Madhya Pradesh", "Maharashtra", "Uttar Pradesh"],
    "city_trend_score": {"Indore": 98, "Bhopal": 96, "Gwalior": 93, "Mumbai": 82, "Lucknow": 80, "Chennai": 20},
    "festival_relevance": ["Diwali", "Navratri", "Teej"],
    "styleTags": ["chanderi", "silk cotton", "handloom", "gwalior"],
    "local_purchase_count": 3650,
    "local_trending_tag": "Indore & Bhopal Handloom Favorite"
  },
  {
    "id": "jk-01",
    "name": "Hand-Embroidered Kashmiri Aari & Tilla Work Silk Pheran",
    "price": 3999,
    "category": "ethnic wear",
    "gender": "women",
    "color": "Maroon & Antique Gold Tilla",
    "pattern": "aari and tilla work",
    "style": "kashmiri pheran",
    "occasion": "festival",
    "image_url": "https://media.gyawun.com/wp-content/uploads/2025/11/kashmiri-raffal-wool-hand-sozni-embroidery-pheran05.webp",
    "brand": "FabIndia",
    "mrp": 6999,
    "discount_percent": 43,
    "rating": 4.9,
    "review_count": 5900,
    "region_relevance": ["Jammu and Kashmir"],
    "city_trend_score": {"Srinagar": 99, "Jammu": 96, "Anantnag": 92, "Delhi": 75, "Chandigarh": 70, "Chennai": 12},
    "festival_relevance": ["Navroz", "Eid", "Winter Festivities"],
    "styleTags": ["pheran", "kashmiri", "tilla work", "aari", "silk pheran"],
    "local_purchase_count": 9200,
    "local_trending_tag": "Srinagar & Jammu Heritage #1 Pick"
  },
  {
    "id": "hp-01",
    "name": "Traditional Kinnauri Handwoven Woolen Shawl & Topi Set",
    "price": 2499,
    "category": "ethnic wear",
    "gender": "unisex",
    "color": "Crimson Red & Geometric Weave",
    "pattern": "geometric weave",
    "style": "kinnauri handwoven",
    "occasion": "festival",
    "image_url": "https://tse4.mm.bing.net/th/id/OIP.nPlFs_gWTa8lKtYXZBQNpgHaHa?r=0&pid=Api&P=0&h=180",
    "brand": "Taavi",
    "mrp": 4299,
    "discount_percent": 42,
    "rating": 4.9,
    "review_count": 5600,
    "region_relevance": ["Himachal Pradesh", "Punjab", "Uttarakhand"],
    "city_trend_score": {"Shimla": 99, "Manali": 97, "Dharamshala": 94, "Chandigarh": 82, "Dehradun": 80, "Goa": 10},
    "festival_relevance": ["Kullu Dussehra", "Halda Festival", "Winter Fairs"],
    "styleTags": ["kinnauri", "woolen shawl", "himachali", "handloom"],
    "local_purchase_count": 8900,
    "local_trending_tag": "Shimla & Manali Traditional Bestseller"
  },
  {
    "id": "uk-01",
    "name": "Garhwali & Kumaoni Traditional Pichora Red-Yellow Zari Dupatta Set",
    "price": 1899,
    "category": "ethnic wear",
    "gender": "women",
    "color": "Kesar Yellow & Swastik Red",
    "pattern": "swastik zari print",
    "style": "pichora dupatta",
    "occasion": "wedding",
    "image_url": "https://tse4.mm.bing.net/th/id/OIP.lyudyqxy0CYdquTcr8ST6gHaJ4?r=0&pid=Api&P=0&h=180",
    "brand": "FabIndia",
    "mrp": 3299,
    "discount_percent": 42,
    "rating": 4.9,
    "review_count": 5500,
    "region_relevance": ["Uttarakhand", "Delhi", "Uttar Pradesh"],
    "city_trend_score": {"Dehradun": 98, "Nainital": 96, "Almora": 95, "Haridwar": 90, "Delhi": 78, "Mumbai": 15},
    "festival_relevance": ["Phool Dei", "Nanda Devi Raj Jat", "Weddings"],
    "styleTags": ["pichora", "garhwali", "kumaoni", "zari dupatta", "uttarakhand"],
    "local_purchase_count": 8700,
    "local_trending_tag": "Dehradun & Nainital Festive Heritage Choice"
  },
  {
    "id": "ap-01",
    "name": "Dharmavaram Pure Handloom Gold Zari Silk Saree",
    "price": 5299,
    "category": "saree",
    "gender": "women",
    "color": "Royal Red & Mango Yellow",
    "pattern": "heavy zari border",
    "style": "dharmavaram silk",
    "occasion": "wedding",
    "image_url": "https://www.nalli.com/cdn/shop/files/NF2958494_M.jpg?v=1769777916&width=1024",
    "brand": "Nalli",
    "mrp": 9500,
    "discount_percent": 44,
    "rating": 4.9,
    "review_count": 5800,
    "region_relevance": ["Andhra Pradesh", "Telangana", "Karnataka"],
    "city_trend_score": {"Visakhapatnam": 98, "Vijayawada": 97, "Tirupati": 94, "Hyderabad": 91, "Bengaluru": 85, "Kolkata": 18},
    "festival_relevance": ["Sankranti", "Ugadi", "Weddings"],
    "styleTags": ["dharmavaram", "pure silk", "gold zari", "andhra silk"],
    "local_purchase_count": 9100,
    "local_trending_tag": "Visakhapatnam & Vijayawada Wedding Bestseller"
  },
  {
    "id": "cg-01",
    "name": "Pure Kosa Silk Handloom Tussar Saree",
    "price": 4199,
    "category": "saree",
    "gender": "women",
    "color": "Natural Beige & Rust Maroon",
    "pattern": "handloom texture",
    "style": "kosa tussar",
    "occasion": "festival",
    "image_url": "https://tse1.mm.bing.net/th/id/OIP._rJKjKyT7Zys-alcH_5huQHaHa?r=0&pid=Api&P=0&h=180",
    "brand": "FabIndia",
    "mrp": 7200,
    "discount_percent": 42,
    "rating": 4.8,
    "review_count": 5400,
    "region_relevance": ["Chhattisgarh", "Madhya Pradesh", "Odisha"],
    "city_trend_score": {"Raipur": 98, "Bilaspur": 96, "Durg": 92, "Bhopal": 83, "Bhubaneswar": 80, "Chennai": 16},
    "festival_relevance": ["Bastar Dussehra", "Polu Festival", "Teej"],
    "styleTags": ["kosa silk", "tussar", "handloom", "chhattisgarh"],
    "local_purchase_count": 8600,
    "local_trending_tag": "Raipur & Bilaspur Kosa Silk Choice"
  },
  {
    "id": "meg-01",
    "name": "Traditional Organic Eri Silk Jainsem Set",
    "price": 3899,
    "category": "ethnic wear",
    "gender": "women",
    "color": "Pastel Peach & Khasi Gold",
    "pattern": "traditional woven",
    "style": "jainsem",
    "occasion": "festival",
    "image_url": "https://tse1.mm.bing.net/th/id/OIP.136yI5V72I2vGyZmTBiQiwHaN7?r=0&pid=Api&P=0&h=180",
    "brand": "Taavi",
    "mrp": 6500,
    "discount_percent": 40,
    "rating": 4.9,
    "review_count": 5200,
    "region_relevance": ["Meghalaya", "Assam"],
    "city_trend_score": {"Shillong": 99, "Tura": 95, "Jowai": 93, "Guwahati": 84, "Kolkata": 65, "Ahmedabad": 10},
    "festival_relevance": ["Shad Suk Mynsiem", "Nongkrem Dance", "Christmas"],
    "styleTags": ["jainsem", "eri silk", "khasi", "handloom", "meghalaya"],
    "local_purchase_count": 8400,
    "local_trending_tag": "Shillong Heritage Traditional Outfit"
  },
  {
    "id": "tri-01",
    "name": "Traditional Tripura Handwoven Rignai & Risa Outfit",
    "price": 2999,
    "category": "ethnic wear",
    "gender": "women",
    "color": "Royal Maroon & Handwoven Gold",
    "pattern": "tribal stripe weave",
    "style": "rignai and risa",
    "occasion": "festival",
    "image_url": "https://tse4.mm.bing.net/th/id/OIP.gTqZ8x4bBPLWNYfrvBg0dgHaK7?r=0&pid=Api&P=0&h=180",
    "brand": "Taavi",
    "mrp": 4999,
    "discount_percent": 40,
    "rating": 4.8,
    "review_count": 5100,
    "region_relevance": ["Tripura", "Assam"],
    "city_trend_score": {"Agartala": 99, "Udaipur": 94, "Dharmanagar": 91, "Guwahati": 82, "Kolkata": 70, "Mumbai": 12},
    "festival_relevance": ["Garia Puja", "Kharchi Puja", "Durga Puja"],
    "styleTags": ["rignai", "risa", "handloom", "tripura"],
    "local_purchase_count": 8300,
    "local_trending_tag": "Agartala Cultural Festival Choice"
  },
  {
    "id": "nag-01",
    "name": "Authentic Handwoven Naga Tribal Pattern Festive Shawl & Wrap",
    "price": 2799,
    "category": "ethnic wear",
    "gender": "unisex",
    "color": "Black, Red & White Tribal Motifs",
    "pattern": "naga tribal motif",
    "style": "naga shawl",
    "occasion": "festival",
    "image_url": "https://tse3.mm.bing.net/th/id/OIP.pMAcKVwrWMzN1O5lFv18WQHaJ4?r=0&pid=Api&P=0&h=180",
    "brand": "Taavi",
    "mrp": 4500,
    "discount_percent": 38,
    "rating": 4.9,
    "review_count": 5700,
    "region_relevance": ["Nagaland", "Assam", "Manipur"],
    "city_trend_score": {"Kohima": 99, "Dimapur": 96, "Mokokchung": 93, "Imphal": 85, "Guwahati": 82, "Delhi": 25},
    "festival_relevance": ["Hornbill Festival", "Sekrenyi", "Moatsu"],
    "styleTags": ["naga shawl", "tribal motif", "handwoven", "nagaland"],
    "local_purchase_count": 8800,
    "local_trending_tag": "Kohima Hornbill Festival Essential"
  },
  {
    "id": "miz-01",
    "name": "Traditional Puanchei Handloom Festive Dress",
    "price": 3199,
    "category": "ethnic wear",
    "gender": "women",
    "color": "White, Black & Red Geometric Weave",
    "pattern": "geometric handloom",
    "style": "puanchei",
    "occasion": "festival",
    "image_url": "https://onlinemizoram.com/wp-content/uploads/2023/11/EXL_1873-scaled.jpg",
    "brand": "Taavi",
    "mrp": 5200,
    "discount_percent": 38,
    "rating": 4.8,
    "review_count": 5300,
    "region_relevance": ["Mizoram", "Assam"],
    "city_trend_score": {"Aizawl": 99, "Lunglei": 95, "Champhai": 92, "Guwahati": 80, "Kolkata": 60, "Bangalore": 15},
    "festival_relevance": ["Chapchar Kut", "Anthurium Festival", "Mim Kut"],
    "styleTags": ["puanchei", "puan", "mizo", "handloom"],
    "local_purchase_count": 8500,
    "local_trending_tag": "Aizawl Chapchar Kut #1 Outfit"
  },
  {
    "id": "man-01",
    "name": "Traditional Handloom Phanek & Innaphi Silk Set",
    "price": 3499,
    "category": "ethnic wear",
    "gender": "women",
    "color": "Lotus Pink & Gold Motif",
    "pattern": "stripe & floral motif",
    "style": "phanek innaphi",
    "occasion": "festival",
    "image_url": "https://www.indiatravel.app/wp-content/uploads/2024/09/Phanek-%E2%80%93-Traditional-Wraparound-for-Manipuri-Women.png",
    "brand": "Taavi",
    "mrp": 5800,
    "discount_percent": 40,
    "rating": 4.9,
    "review_count": 5400,
    "region_relevance": ["Manipur", "Assam"],
    "city_trend_score": {"Imphal": 99, "Thoubal": 94, "Bishnupur": 91, "Guwahati": 82, "Kolkata": 68, "Pune": 12},
    "festival_relevance": ["Yaoshang", "Ningol Chakouba", "Lai Haraoba"],
    "styleTags": ["phanek", "innaphi", "manipuri silk", "handloom"],
    "local_purchase_count": 8700,
    "local_trending_tag": "Imphal Yaoshang Festival Choice"
  },
  {
    "id": "sik-01",
    "name": "Traditional Sikkimese Pure Silk Bakhu / Kho Outfit",
    "price": 3699,
    "category": "ethnic wear",
    "gender": "women",
    "color": "Emerald Brocade Silk",
    "pattern": "brocade pattern",
    "style": "bakhu kho",
    "occasion": "festival",
    "image_url": "https://tse3.mm.bing.net/th/id/OIP.t5OUXeORkzvkktU1wLdldQHaNK?r=0&pid=Api&P=0&h=180",
    "brand": "FabIndia",
    "mrp": 6200,
    "discount_percent": 40,
    "rating": 4.8,
    "review_count": 5200,
    "region_relevance": ["Sikkim", "West Bengal"],
    "city_trend_score": {"Gangtok": 99, "Namchi": 95, "Gyalshing": 92, "Siliguri": 85, "Kolkata": 72, "Hyderabad": 14},
    "festival_relevance": ["Losar", "Saga Dawa", "Lhabab Duchen"],
    "styleTags": ["bakhu", "kho", "sikkim", "brocade silk"],
    "local_purchase_count": 8400,
    "local_trending_tag": "Gangtok Losar Festival Special"
  },
  {
    "id": "ar-01",
    "name": "Traditional Handwoven Gale Ethnic Wrap Dress",
    "price": 2699,
    "category": "ethnic wear",
    "gender": "women",
    "color": "Red & Black Stripe Handwoven",
    "pattern": "striped handwoven",
    "style": "gale wrap",
    "occasion": "festival",
    "image_url": "https://i.pinimg.com/736x/b7/02/e6/b702e67ffd0779a87d4c698fa1b2e4ca.jpg",
    "brand": "Taavi",
    "mrp": 4400,
    "discount_percent": 39,
    "rating": 4.7,
    "review_count": 5000,
    "region_relevance": ["Arunachal Pradesh", "Assam"],
    "city_trend_score": {"Itanagar": 99, "Naharlagun": 95, "Pasighat": 92, "Guwahati": 81, "Kolkata": 62, "Jaipur": 10},
    "festival_relevance": ["Solung", "Losar", "Nyokum"],
    "styleTags": ["gale", "arunachal", "handwoven", "tribal wrap"],
    "local_purchase_count": 8200,
    "local_trending_tag": "Itanagar Solung Festival Choice"
  },
  {
    "id": "west-m-01",
    "name": "Slim Fit Pure Linen Casual Shirt",
    "price": 1299,
    "category": "western wear",
    "gender": "men",
    "color": "Sky Blue",
    "pattern": "solid",
    "style": "linen casual shirt",
    "occasion": "casual",
    "image_url": "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&auto=format&fit=crop&q=80",
    "brand": "Roadster",
    "mrp": 2499,
    "discount_percent": 48,
    "rating": 4.5,
    "review_count": 3400,
    "region_relevance": ["Karnataka", "Maharashtra", "Tamil Nadu", "Delhi", "Punjab"],
    "city_trend_score": {"Bengaluru": 98, "Mumbai": 96, "Pune": 92, "Delhi": 89, "Chennai": 87, "Patna": 45},
    "festival_relevance": ["Summer Socials", "College Fest", "Weekend Outings"],
    "styleTags": ["linen", "breathable", "summer", "casual"],
    "local_purchase_count": 5400,
    "local_trending_tag": "Bengaluru & Mumbai Tech Park Favorite"
  },
  {
    "id": "west-w-01",
    "name": "Floral Print Tiered Midi Western Dress",
    "price": 1499,
    "category": "western wear",
    "gender": "women",
    "color": "Pastel Floral",
    "pattern": "floral print",
    "style": "midi dress",
    "occasion": "casual",
    "image_url": "https://sassafras.in/cdn/shop/files/SFDRSS13730-1_1300x.jpg?v=1778664956",
    "brand": "DressBerry",
    "mrp": 2999,
    "discount_percent": 50,
    "rating": 4.6,
    "review_count": 2800,
    "region_relevance": ["Maharashtra", "Karnataka", "Delhi", "Punjab", "Rajasthan"],
    "city_trend_score": {"Mumbai": 97, "Pune": 95, "Bengaluru": 94, "Delhi": 90, "Chandigarh": 86, "Gaya": 25},
    "festival_relevance": ["Brunch Gatherings", "Summer Socials", "New Year"],
    "styleTags": ["floral", "western dress", "summer", "boho"],
    "local_purchase_count": 4300,
    "local_trending_tag": "Mumbai & Pune Cafe Trend"
  },
  {
    "id": "west-m-02",
    "name": "Classic Trucker Denim Jacket",
    "price": 2799,
    "category": "western wear",
    "gender": "men",
    "color": "Indigo Blue",
    "pattern": "solid denim",
    "style": "trucker jacket",
    "occasion": "casual",
    "image_url": "https://images.unsplash.com/photo-1537465978529-d23b17165b3b?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "brand": "Levis",
    "mrp": 4999,
    "discount_percent": 44,
    "rating": 4.7,
    "review_count": 2500,
    "region_relevance": ["Punjab", "Uttar Pradesh", "Delhi", "Rajasthan", "Bihar"],
    "city_trend_score": {"Chandigarh": 98, "Delhi": 96, "Ludhiana": 94, "Jaipur": 88, "Lucknow": 85, "Kochi": 30},
    "festival_relevance": ["Winter Fest", "New Year", "Concerts"],
    "styleTags": ["denim", "jacket", "winter", "streetwear"],
    "local_purchase_count": 3890,
    "local_trending_tag": "Chandigarh & Delhi Winter Streetwear"
  },
  {
    "id": "west-w-02",
    "name": "High-Rise Wide Leg Tapered Jeans",
    "price": 1199,
    "category": "western wear",
    "gender": "women",
    "color": "Light Wash Blue",
    "pattern": "washed solid",
    "style": "wide leg jeans",
    "occasion": "casual",
    "image_url": "https://media.landmarkshops.in/cdn-cgi/image/h=831,w=615,q=85,fit=cover/max-new/1000015583346-Blue-LIGHTBLUE-1000015583346_01-2100.jpg",
    "brand": "HIGHLANDER",
    "mrp": 2299,
    "discount_percent": 48,
    "rating": 4.6,
    "review_count": 3100,
    "region_relevance": ["Maharashtra", "Karnataka", "Uttar Pradesh", "Punjab", "Bihar"],
    "city_trend_score": {"Patna": 96, "Lucknow": 95, "Mumbai": 92, "Bengaluru": 90, "Ludhiana": 87, "Madurai": 32},
    "festival_relevance": ["College Fest", "Casual Hangouts", "Youth Events"],
    "styleTags": ["denim", "wide leg", "high rise", "trending"],
    "local_purchase_count": 4950,
    "local_trending_tag": "Patna & Lucknow Youth Favorite"
  },
  {
    "id": "west-m-03",
    "name": "Oversized Graphic Printed Streetwear Hoodie",
    "price": 1599,
    "category": "western wear",
    "gender": "men",
    "color": "Charcoal Grey",
    "pattern": "graphic print",
    "style": "oversized hoodie",
    "occasion": "casual",
    "image_url": "https://plus.unsplash.com/premium_photo-1673827311290-d435f481152e?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "brand": "HRX",
    "mrp": 2999,
    "discount_percent": 47,
    "rating": 4.6,
    "review_count": 2300,
    "region_relevance": ["Punjab", "Uttar Pradesh", "Delhi", "Maharashtra"],
    "city_trend_score": {"Ludhiana": 98, "Amritsar": 96, "Delhi": 93, "Lucknow": 86, "Mumbai": 80, "Chennai": 22},
    "festival_relevance": ["Winter Fests", "College Culture", "Youth Concerts"],
    "styleTags": ["hoodie", "oversized", "streetwear", "cotton"],
    "local_purchase_count": 3600,
    "local_trending_tag": "Ludhiana & Amritsar College Pick"
  },
  {
    "id": "west-w-03",
    "name": "Structured Formal Blazer for Women",
    "price": 3299,
    "category": "western wear",
    "gender": "women",
    "color": "Classic Black",
    "pattern": "solid",
    "style": "formal blazer",
    "occasion": "work",
    "image_url": "https://www.powersutra.co/cdn/shop/files/236.png?v=1780659642&width=1000",
    "brand": "MANGO",
    "mrp": 5999,
    "discount_percent": 45,
    "rating": 4.8,
    "review_count": 1900,
    "region_relevance": ["Maharashtra", "Karnataka", "Tamil Nadu", "Delhi"],
    "city_trend_score": {"Mumbai": 98, "Bengaluru": 97, "Delhi": 94, "Chennai": 91, "Gurugram": 95, "Ranchi": 28},
    "festival_relevance": ["Corporate Events", "Business Summits", "Workplace Celebrations"],
    "styleTags": ["blazer", "formal", "workwear", "chic"],
    "local_purchase_count": 3100,
    "local_trending_tag": "Corporate Workwear Bestseller"
  },
  {
    "id": "goa-01",
    "name": "Coastal Resort Linen Printed Shirt",
    "price": 1399,
    "category": "western wear",
    "gender": "men",
    "color": "Oceanic Floral Blue",
    "pattern": "floral print",
    "style": "resort shirt",
    "occasion": "casual",
    "image_url": "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&auto=format&fit=crop&q=80",
    "brand": "Roadster",
    "mrp": 2599,
    "discount_percent": 46,
    "rating": 4.7,
    "review_count": 2700,
    "region_relevance": ["Goa", "Maharashtra", "Karnataka"],
    "city_trend_score": {"Panaji": 99, "Margao": 96, "Mumbai": 92, "Bengaluru": 88, "Pune": 86, "Kanpur": 20},
    "festival_relevance": ["Goa Carnival", "Sunburn", "Beach Holidays"],
    "styleTags": ["resort wear", "linen", "coastal", "goa fashion"],
    "local_purchase_count": 4100,
    "local_trending_tag": "Panaji & Goa Resort Favorite"
  },
  {
    "id": "pun-03",
    "name": "Hand-Embroidered Velvet Punjabi Jutti",
    "price": 1499,
    "category": "footwear",
    "gender": "women",
    "color": "Royal Maroon & Gold",
    "pattern": "embroidered",
    "style": "punjabi jutti",
    "occasion": "festival",
    "image_url": "https://i.pinimg.com/736x/53/b3/30/53b330770e59a4f26376f882661ab290.jpg",
    "brand": "House of Pataudi",
    "mrp": 2999,
    "discount_percent": 50,
    "rating": 4.8,
    "review_count": 4400,
    "region_relevance": ["Punjab", "Rajasthan", "Delhi", "Uttar Pradesh", "Haryana"],
    "city_trend_score": {"Amritsar": 99, "Ludhiana": 96, "Jaipur": 91, "Delhi": 89, "Lucknow": 85, "Kochi": 18},
    "festival_relevance": ["Baisakhi", "Karwa Chauth", "Lohri", "Weddings"],
    "styleTags": ["jutti", "hand-embroidered", "punjabi jutti", "mojari"],
    "local_purchase_count": 6850,
    "local_trending_tag": "Amritsar Heritage Craft Bestseller"
  },
  {
    "id": "mah-03",
    "name": "Handcrafted Genuine Leather Kolhapuri Chappal",
    "price": 1299,
    "category": "footwear",
    "gender": "men",
    "color": "Tan Brown",
    "pattern": "handcrafted weave",
    "style": "kolhapuri chappal",
    "occasion": "casual",
    "image_url": "https://vhaan.in/cdn/shop/products/1_3dc7172d-e255-4647-97b8-9b7ffb6b2876.jpg?v=1706529650&width=1200",
    "brand": "Taavi",
    "mrp": 2499,
    "discount_percent": 48,
    "rating": 4.9,
    "review_count": 4600,
    "region_relevance": ["Maharashtra", "Karnataka", "Gujarat", "Goa"],
    "city_trend_score": {"Kolhapur": 99, "Pune": 97, "Mumbai": 94, "Belgaum": 91, "Panaji": 85, "Patna": 22},
    "festival_relevance": ["Ganesh Chaturthi", "Gudi Padwa", "Festive Weddings"],
    "styleTags": ["kolhapuri", "leather", "ethnic footwear", "handcrafted"],
    "local_purchase_count": 7120,
    "local_trending_tag": "Kolhapur & Pune Craft Special"
  },
  {
    "id": "raj-03",
    "name": "Royal Camel Leather Embroidered Mojari",
    "price": 1699,
    "category": "footwear",
    "gender": "men",
    "color": "Antique Gold",
    "pattern": "embroidered",
    "style": "mojari",
    "occasion": "wedding",
    "image_url": "https://imgs.search.brave.com/c_5iEabz8sQWBL5mcRne1zE1js0znu4J24YdaIgTRbw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9ob3Vz/ZW9mbWFydGluLmlu/L2Nkbi9zaG9wL2Zp/bGVzL2ltYWdlMDAw/MDVfNF8xLmpwZz92/PTE3NTk4NjkxODMm/d2lidGg9Mzg0MA",
    "brand": "KRA",
    "mrp": 3299,
    "discount_percent": 48,
    "rating": 4.8,
    "review_count": 3500,
    "region_relevance": ["Rajasthan", "Uttar Pradesh", "Punjab", "Bihar"],
    "city_trend_score": {"Jaipur": 98, "Jodhpur": 97, "Lucknow": 89, "Patna": 84, "Amritsar": 82, "Chennai": 20},
    "festival_relevance": ["Weddings", "Diwali", "Teej"],
    "styleTags": ["mojari", "jaipuri", "ethnic footwear", "embroidered"],
    "local_purchase_count": 5410,
    "local_trending_tag": "Jaipur & Jodhpur Groom Choice"
  },
  {
    "id": "foot-01",
    "name": "Cushioned Lightweight Breathable Running Sneakers",
    "price": 2499,
    "category": "footwear",
    "gender": "unisex",
    "color": "Vibrant Red & White",
    "pattern": "mesh panel",
    "style": "running sneakers",
    "occasion": "casual",
    "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80",
    "brand": "Puma",
    "mrp": 4999,
    "discount_percent": 50,
    "rating": 4.7,
    "review_count": 4300,
    "region_relevance": ["Maharashtra", "Punjab", "Uttar Pradesh", "Karnataka", "Bihar", "Tamil Nadu"],
    "city_trend_score": {"Mumbai": 95, "Bengaluru": 94, "Delhi": 92, "Chandigarh": 90, "Chennai": 88, "Patna": 85},
    "festival_relevance": ["Marathons", "Fitness Fests", "Daily Casual"],
    "styleTags": ["sneakers", "running", "breathable", "comfort"],
    "local_purchase_count": 6700,
    "local_trending_tag": "Pan-India Sports & Casual Favorite"
  },
  {
    "id": "foot-02",
    "name": "Hand-Stitched Genuine Leather Penny Loafers",
    "price": 2199,
    "category": "footwear",
    "gender": "men",
    "color": "Deep Mahogany",
    "pattern": "solid leather",
    "style": "penny loafers",
    "occasion": "work",
    "image_url": "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600&auto=format&fit=crop&q=80",
    "brand": "Bata",
    "mrp": 3999,
    "discount_percent": 45,
    "rating": 4.6,
    "review_count": 2500,
    "region_relevance": ["Uttar Pradesh", "Bihar", "Maharashtra", "Tamil Nadu", "Punjab"],
    "city_trend_score": {"Kanpur": 98, "Lucknow": 94, "Patna": 90, "Mumbai": 88, "Chennai": 85, "Shimla": 40},
    "festival_relevance": ["Formal Gatherings", "Corporate Events"],
    "styleTags": ["formal", "leather", "loafers", "workwear"],
    "local_purchase_count": 3890,
    "local_trending_tag": "Kanpur Leather Heritage Pick"
  },
  {
    "id": "foot-03",
    "name": "Strappy Block Heel Festive Metallic Sandals",
    "price": 1799,
    "category": "footwear",
    "gender": "women",
    "color": "Rose Gold",
    "pattern": "metallic shine",
    "style": "block heels",
    "occasion": "wedding",
    "image_url": "https://imgs.search.brave.com/PDvzvji5lCQPWY5V1Np5gOfHleDhuG90Y2-g_Pi8tds/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMubGFjZWFuZGZh/dm91ci5jb20vX2Nh/Y2hlL19wcm9kdWN0/cy84NTB4ODUwL3Jh/aW5ib3ctY2x1Yi1t/YXJnb3Qtcm9zZS1n/b2xkLW1ldGFsbGlj/LW1pZC1ibG9jay1o/ZWVsLXNhbmRhbHMt/cGFpci5qcGc",
    "brand": "Catwalk",
    "mrp": 3299,
    "discount_percent": 45,
    "rating": 4.7,
    "review_count": 2700,
    "region_relevance": ["Maharashtra", "Rajasthan", "Uttar Pradesh", "Tamil Nadu", "Bihar", "Punjab"],
    "city_trend_score": {"Mumbai": 96, "Jaipur": 94, "Lucknow": 91, "Chennai": 88, "Patna": 85, "Shillong": 30},
    "festival_relevance": ["Weddings", "Sangeet", "Diwali Parties"],
    "styleTags": ["heels", "sandals", "festive", "gold"],
    "local_purchase_count": 4200,
    "local_trending_tag": "Wedding Season Must-Have"
  },
  {
    "id": "acc-w-01",
    "name": "Temple Jewellery Gold-Plated Kundan Necklace Set",
    "price": 1499,
    "category": "accessories",
    "gender": "women",
    "color": "Antique Gold",
    "pattern": "kundan temple work",
    "style": "temple jewelry",
    "occasion": "wedding",
    "image_url": "https://i.pinimg.com/736x/bc/48/8f/bc488fcea30c597aa1f03bbb1de0959d.jpg",
    "brand": "Zaveri Pearls",
    "mrp": 3999,
    "discount_percent": 63,
    "rating": 4.8,
    "review_count": 3900,
    "region_relevance": ["Tamil Nadu", "Karnataka", "Kerala", "Maharashtra", "Rajasthan"],
    "city_trend_score": {"Madurai": 99, "Chennai": 98, "Bengaluru": 93, "Kochi": 90, "Mumbai": 86, "Amritsar": 25},
    "festival_relevance": ["Weddings", "Varalakshmi Vratam", "Diwali"],
    "styleTags": ["traditional", "kundan", "bridal", "temple jewelry"],
    "local_purchase_count": 5900,
    "local_trending_tag": "Madurai & Chennai Wedding Pick"
  },
  {
    "id": "up-03",
    "name": "Handworked Zardozi Velvet Bridal Potli Bag",
    "price": 1299,
    "category": "accessories",
    "gender": "women",
    "color": "Royal Velvet Red",
    "pattern": "zardozi embroidery",
    "style": "potli bag",
    "occasion": "wedding",
    "image_url": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80",
    "brand": "Sabyasachi Collection",
    "mrp": 2499,
    "discount_percent": 48,
    "rating": 4.8,
    "review_count": 2600,
    "region_relevance": ["Uttar Pradesh", "Rajasthan", "Punjab", "Bihar"],
    "city_trend_score": {"Varanasi": 98, "Lucknow": 96, "Jaipur": 92, "Ludhiana": 88, "Patna": 85, "Kochi": 18},
    "festival_relevance": ["Weddings", "Sangeet", "Karwa Chauth"],
    "styleTags": ["potli bag", "zardozi", "velvet", "bridal accessory"],
    "local_purchase_count": 4150,
    "local_trending_tag": "Varanasi & Lucknow Wedding Accessory"
  },
  {
    "id": "acc-m-01",
    "name": "Handcrafted Genuine Leather RFID Blocking Wallet",
    "price": 899,
    "category": "accessories",
    "gender": "men",
    "color": "Rustic Brown",
    "pattern": "solid leather",
    "style": "bifold wallet",
    "occasion": "casual",
    "image_url": "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80",
    "brand": "WildHorn",
    "mrp": 1999,
    "discount_percent": 55,
    "rating": 4.7,
    "review_count": 3100,
    "region_relevance": ["Uttar Pradesh", "Maharashtra", "Punjab", "Bihar", "Tamil Nadu"],
    "city_trend_score": {"Agra": 98, "Kanpur": 96, "Lucknow": 92, "Mumbai": 89, "Chennai": 84, "Imphal": 30},
    "festival_relevance": ["Diwali Gifting", "Father's Day", "Daily Use"],
    "styleTags": ["leather", "wallet", "rfid", "handcrafted"],
    "local_purchase_count": 4900,
    "local_trending_tag": "Agra & Kanpur Leather Craft"
  },
  {
    "id": "acc-01",
    "name": "Unisex Classic UV Protected Aviator Sunglasses",
    "price": 3499,
    "category": "accessories",
    "gender": "unisex",
    "color": "Golden Frame Dark Green",
    "pattern": "solid metallic frame",
    "style": "aviator sunglasses",
    "occasion": "casual",
    "image_url": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80",
    "brand": "Ray-Ban",
    "mrp": 5999,
    "discount_percent": 42,
    "rating": 4.9,
    "review_count": 3600,
    "region_relevance": ["Punjab", "Maharashtra", "Delhi", "Rajasthan", "Karnataka"],
    "city_trend_score": {"Chandigarh": 98, "Delhi": 97, "Mumbai": 95, "Jaipur": 91, "Bengaluru": 90, "Gaya": 40},
    "festival_relevance": ["Summer Roadtrips", "Music Festivals", "Casual Outings"],
    "styleTags": ["sunglasses", "aviator", "classic", "uv protection"],
    "local_purchase_count": 5300,
    "local_trending_tag": "Top Rated Style Accessory"
  },
  {
    "id": "acc-02",
    "name": "Full-Touch HD AMOLED Bluetooth Calling Smartwatch",
    "price": 2299,
    "category": "accessories",
    "gender": "unisex",
    "color": "Matte Black",
    "pattern": "digital smart display",
    "style": "smartwatch",
    "occasion": "casual",
    "image_url": "https://imgs.search.brave.com/YKlHQQN2X2-t_WE9TZItFmG16EoMv7O4PMo48f1_I-c/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbi5h/bWF6Zml0LmNvbS9j/ZG4vc2hvcC9maWxl/cy8zXzItc3dfZTM1/MjgwYTctY2E0MC00/NzI0LWI3MGMtYzI1/ZjMxYzg3OWYxLnBu/Zz92PTE3MDc5NzU5/MjImd2lkdGg9MzAw",
    "brand": "Noise",
    "mrp": 4999,
    "discount_percent": 54,
    "rating": 4.6,
    "review_count": 4000,
    "region_relevance": ["Maharashtra", "Karnataka", "Punjab", "Uttar Pradesh", "Bihar", "Tamil Nadu"],
    "city_trend_score": {"Bengaluru": 97, "Mumbai": 96, "Delhi": 94, "Pune": 92, "Ludhiana": 89, "Patna": 85},
    "festival_relevance": ["Diwali Gifting", "New Year Resolutions", "Tech Events"],
    "styleTags": ["smartwatch", "amoled", "fitness", "tech"],
    "local_purchase_count": 6100,
    "local_trending_tag": "Tech-Forward Essential"
  },
  {
    "id": "acc-03",
    "name": "Traditional Kundan Chandelier Pearl Jhumka Earrings",
    "price": 999,
    "category": "accessories",
    "gender": "women",
    "color": "Pearl White & Gold",
    "pattern": "kundan pearl drop",
    "style": "jhumka earrings",
    "occasion": "festival",
    "image_url": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80",
    "brand": "Rubans",
    "mrp": 2199,
    "discount_percent": 55,
    "rating": 4.8,
    "review_count": 3500,
    "region_relevance": ["Rajasthan", "Punjab", "Uttar Pradesh", "Bihar", "Maharashtra"],
    "city_trend_score": {"Jaipur": 98, "Amritsar": 95, "Lucknow": 93, "Patna": 90, "Mumbai": 87, "Kochi": 22},
    "festival_relevance": ["Diwali", "Karwa Chauth", "Navratri", "Weddings"],
    "styleTags": ["jhumka", "kundan", "pearls", "ethnic jewelry"],
    "local_purchase_count": 5400,
    "local_trending_tag": "Festive Pearl Jhumka Bestseller"
  }
]